name: CI - Windows Push

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/windows-reusable-push.yml@fewarp_test
    with:
      aws-ami-id: ami-0f458bdce73864228
      aws-sg-id: sg-0ca7912782cf1538b
      aws-instance-type: c5a.8xlarge
      runTests: false
      package-name: febiowarp
      requires-sdk: true
    secrets: inherit
